# Generated by Django 5.0.6 on 2024-06-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uptimereports',
            name='store_id',
        ),
        migrations.AlterField(
            model_name='uptimereports',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
